version: '3'

services:
  db:
    image: mysql
    container_name: db-001
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql